const $ = (id) => document.getElementById(id);
const input = $('chartInput');
const dropzone = $('dropzone');
const previewWrap = $('previewWrap');
const preview = $('chartPreview');
const analyzeBtn = $('analyzeBtn');
let imageReady = false;
let imageDataUrl = '';
let liveMarket = null;
let liveNews = [];
let liveCalendar = [];
let localVisual = null;
const TV_SYMBOLS = {XAUUSD:'OANDA:XAUUSD',XAGUSD:'OANDA:XAGUSD',BTCUSD:'COINBASE:BTCUSD',ETHUSD:'COINBASE:ETHUSD',SOLUSD:'COINBASE:SOLUSD',US30:'CAPITALCOM:US30',NAS100:'CAPITALCOM:NAS100',SPX500:'CAPITALCOM:SPX500',EURUSD:'OANDA:EURUSD',GBPUSD:'OANDA:GBPUSD',USDJPY:'OANDA:USDJPY',AUDUSD:'OANDA:AUDUSD'};
const TV_INTERVALS = {'5M':'5','15M':'15','1H':'60','4H':'240','1D':'D'};
const DATA_INTERVALS = {'5M':'5m','15M':'15m','1H':'1h','4H':'4h','1D':'1d'};
function setText(id,value){if($(id))$(id).textContent=value??'—';}
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function formatDate(value){if(!value)return'—';const d=new Date(value);return Number.isNaN(d.getTime())?value:d.toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'});}
function formatPrice(value){if(value===null||value===undefined||!Number.isFinite(Number(value)))return'—';return Number(value).toLocaleString(undefined,{maximumFractionDigits:Number(value)<10?6:2});}
async function fetchJson(url,options={}){const r=await fetch(url,{cache:'no-store',...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);return d;}
function showPreview(file){if(!file)return;if(!file.type?.toLowerCase().startsWith('image/'))return alert('Please select an image file.');if(file.size>10*1024*1024)return alert('Please choose an image smaller than 10 MB.');const reader=new FileReader();reader.onload=()=>{if(typeof reader.result!=='string'||!reader.result.startsWith('data:image/'))return alert('The image could not be loaded.');imageDataUrl=reader.result;preview.onload=()=>{imageReady=true;previewWrap.hidden=false;dropzone.hidden=true;setText('analysisMeta',`${file.name} · chart loaded locally`);localVisual=analyzeChartImage(preview);};preview.onerror=()=>{imageReady=false;imageDataUrl='';localVisual=null;preview.src='';previewWrap.hidden=true;dropzone.hidden=false;alert('Use a PNG or JPG image.');};preview.src=reader.result;};reader.readAsDataURL(file);}
input.addEventListener('change',e=>{const f=e.target.files?.[0];if(f)showPreview(f);});
dropzone.addEventListener('click',e=>{if(e.target!==input)input.click();});
dropzone.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();input.click();}});
['dragenter','dragover'].forEach(t=>dropzone.addEventListener(t,e=>{e.preventDefault();dropzone.classList.add('dragover');}));
['dragleave','drop'].forEach(t=>dropzone.addEventListener(t,e=>{e.preventDefault();dropzone.classList.remove('dragover');}));
dropzone.addEventListener('drop',e=>{const f=e.dataTransfer?.files?.[0];if(f)showPreview(f);});
$('removeImage').addEventListener('click',()=>{input.value='';preview.src='';previewWrap.hidden=true;dropzone.hidden=false;imageReady=false;imageDataUrl='';localVisual=null;setText('analysisMeta','Ready for local analysis');});
function renderTradingView(){const container=$('tradingview_chart');if(!container)return;const asset=$('asset').value,interval=TV_INTERVALS[$('timeframe').value]||'5',symbol=TV_SYMBOLS[asset]||TV_SYMBOLS.XAUUSD;setText('tvStatus','LOADING');setText('heroAsset',asset);setText('heroPrice','—');setText('providerSymbol',symbol);setText('quoteCaptured',$('timeframe').value);setText('currentPrice','See TradingView');setText('currentPriceNote',`${asset} · ${$('timeframe').value}`);setText('sourceNote',`${symbol} · live embedded chart`);container.innerHTML='<div class="tradingview-widget-container" style="height:100%;width:100%"><div class="tradingview-widget-container__widget" style="height:calc(100% - 32px);width:100%"></div><div class="tradingview-widget-copyright"><a href="https://www.tradingview.com/" rel="noopener nofollow" target="_blank"><span class="blue-text">Chart</span></a><span class="trademark"> by TradingView</span></div></div>';const widget=container.querySelector('.tradingview-widget-container__widget');const script=document.createElement('script');script.type='text/javascript';script.src='https://s3.tradingview.com/external-embedding/embed-widget-advanced-chart.js';script.async=true;script.innerHTML=JSON.stringify({autosize:true,symbol,interval,timezone:'Africa/Johannesburg',theme:'dark',style:'1',locale:'en',allow_symbol_change:false,hide_side_toolbar:false,hide_top_toolbar:false,hide_legend:false,hide_volume:false,withdateranges:true,save_image:false,calendar:false,details:false,hotlist:false,support_host:'https://www.tradingview.com'});script.addEventListener('error',()=>{container.innerHTML='<div class="tv-error">TradingView chart failed to load.</div>';setText('tvStatus','LOAD ERROR');});widget.appendChild(script);setText('tvStatus','LIVE CHART');}
function sma(values,period){if(values.length<period)return null;const s=values.slice(-period);return s.reduce((a,b)=>a+b,0)/period;}
function ema(values,period){if(values.length<period)return null;const m=2/(period+1);let e=values.slice(0,period).reduce((a,b)=>a+b,0)/period;for(let i=period;i<values.length;i++)e=(values[i]-e)*m+e;return e;}
function rsi(values,period=14){if(values.length<=period)return null;let gain=0,loss=0;for(let i=1;i<=period;i++){const d=values[i]-values[i-1];if(d>=0)gain+=d;else loss-=d;}let ag=gain/period,al=loss/period;for(let i=period+1;i<values.length;i++){const d=values[i]-values[i-1];ag=((ag*(period-1))+Math.max(d,0))/period;al=((al*(period-1))+Math.max(-d,0))/period;}if(al===0)return 100;return 100-(100/(1+ag/al));}
function atr(candles,period=14){if(candles.length<=period)return null;const tr=[];for(let i=1;i<candles.length;i++){const c=candles[i],p=candles[i-1];tr.push(Math.max(c.high-c.low,Math.abs(c.high-p.close),Math.abs(c.low-p.close)));}return sma(tr,period);}
function enrichMarket(candles){if(!Array.isArray(candles)||candles.length<50)return null;const closes=candles.map(c=>Number(c.close));const latest=candles[candles.length-1],previous=candles[candles.length-2];const ema20=ema(closes,20),ema50=ema(closes,50),rsi14=rsi(closes,14),atr14=atr(candles,14);const recent=candles.slice(-20);const support=Math.min(...recent.map(c=>Number(c.low)));const resistance=Math.max(...recent.map(c=>Number(c.high)));let structure='NEUTRAL';if(ema20&&ema50&&latest.close>ema20&&ema20>ema50)structure='BULLISH';else if(ema20&&ema50&&latest.close<ema20&&ema20<ema50)structure='BEARISH';return{price:Number(latest.close),changePercent:previous?((latest.close-previous.close)/previous.close)*100:0,indicators:{ema20,ema50,rsi14,atr14,support,resistance,structure}};}
async function getLocalMt5Market(asset,timeframe){try{const interval=DATA_INTERVALS[timeframe]||'5m';const url=`http://127.0.0.1:8765/candles?asset=${encodeURIComponent(asset)}&interval=${encodeURIComponent(interval)}&limit=200`;const d=await fetchJson(url);if(!d.ok||!Array.isArray(d.candles)||d.candles.length<50)throw new Error(d.details||'Local MT5 returned insufficient candles');const calc=enrichMarket(d.candles);if(!calc)throw new Error('Could not calculate indicators from MT5 candles');let quote=null;try{quote=await fetchJson(`http://127.0.0.1:8765/quote?symbol=${encodeURIComponent(d.providerSymbol)}`);}catch(e){}return{ok:true,asset,provider:'Exness MT5',providerSymbol:d.providerSymbol,timeframe,timestamp:d.timestamp||new Date().toISOString(),price:quote?.price??calc.price,bid:quote?.bid??null,ask:quote?.ask??null,changePercent:calc.changePercent,indicators:calc.indicators,candles:d.candles,marketState:'LOCAL MT5 OHLC + LIVE QUOTE',chartAnalysis:imageReady?'Local screenshot analyzed':'No chart screenshot supplied',dataAvailable:true,note:'Read-only broker data from the local MT5 terminal.'};}catch(e){return null;}}
async function buildMarketContext(){const asset=$('asset').value,timeframe=$('timeframe').value;let data=null;if(asset==='XAUUSD'){data=await getLocalMt5Market(asset,timeframe);}if(!data){try{data=await fetchJson(`/api/market-data?asset=${encodeURIComponent(asset)}&interval=${encodeURIComponent(DATA_INTERVALS[timeframe]||'15m')}&fresh=${Date.now()}`);}catch(e){data={ok:false,message:e.message};}}if(data.ok){setText('heroPrice',formatPrice(data.price));setText('currentPrice',formatPrice(data.price));setText('currentPriceNote',`${asset} · live OHLC data · ${data.provider}`);setText('sourceNote',`${data.providerSymbol} · ${data.provider}`);setText('providerSymbol',data.providerSymbol);setText('quoteCaptured',formatDate(data.timestamp));}else{setText('heroPrice','—');setText('currentPrice','See TradingView');setText('currentPriceNote',`${asset} · chart available; numeric feed not connected`);}return{ok:true,asset,provider:data.provider||'TradingView',providerSymbol:data.providerSymbol||TV_SYMBOLS[asset]||asset,timeframe,timestamp:data.timestamp||new Date().toISOString(),price:data.price??null,bid:data.bid??null,ask:data.ask??null,changePercent:data.changePercent??null,indicators:data.indicators||null,candles:data.candles||[],marketState:data.ok?'LIVE OHLC + LIVE CHART':'LIVE CHART DISPLAY',chartAnalysis:imageReady?'Local screenshot supplied and analyzed in-browser':'No chart screenshot supplied',dataAvailable:Boolean(data.ok),note:data.note||data.message||'TradingView is the visual chart; machine-readable values are used when available.'};}
function analyzeChartImage(img){try{const w=img.naturalWidth||img.width,h=img.naturalHeight||img.height;if(!w||!h)return null;const canvas=document.createElement('canvas');const scale=Math.min(1,900/w);canvas.width=Math.max(1,Math.round(w*scale));canvas.height=Math.max(1,Math.round(h*scale));const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(img,0,0,canvas.width,canvas.height);const image=ctx.getImageData(0,0,canvas.width,canvas.height);const data=image.data;let red=0,green=0,bright=0,dark=0,ink=0;const cols=new Array(canvas.width).fill(0);const rows=new Array(canvas.height).fill(0);for(let y=0;y<canvas.height;y++){for(let x=0;x<canvas.width;x++){const i=(y*canvas.width+x)*4,r=data[i],g=data[i+1],b=data[i+2],mx=Math.max(r,g,b),mn=Math.min(r,g,b);if(mx>210)bright++;if(mx<70)dark++;const isRed=r>120&&r>g*1.25&&r>b*1.15;const isGreen=g>100&&g>r*1.18&&g>b*1.05;if(isRed){red++;cols[x]++;rows[y]++;}if(isGreen){green++;cols[x]++;rows[y]++;}if(mx-mn>35&&mx>90)ink++;}}const colored=red+green;const visualBias=colored<20?'NEUTRAL':green>red*1.12?'BULLISH':red>green*1.12?'BEARISH':'NEUTRAL';const density=Math.min(100,Math.round((colored/(canvas.width*canvas.height))*10000));const brightRatio=bright/(canvas.width*canvas.height);const darkRatio=dark/(canvas.width*canvas.height);let supportY=null,resistanceY=null;if(colored>20){let maxRow=0,minRow=canvas.height;for(let y=0;y<rows.length;y++){if(rows[y]>2){if(y<minRow)minRow=y;if(y>maxRow)maxRow=y;}}resistanceY=minRow;supportY=maxRow;}return{available:true,width:w,height:h,visualBias,candleColorBalance:{bullishPixels:green,bearishPixels:red},chartDensity:density,background:darkRatio>brightRatio?'DARK':'LIGHT',plotBounds:{top:resistanceY,bottom:supportY},signals:[`Local pixel scan detected ${visualBias.toLowerCase()} candle-color bias.`,`Chart color density: ${density}%.`,`Detected ${green} bullish-color pixels and ${red} bearish-color pixels.`]};}catch(e){return{available:false,signals:['The chart image loaded, but the local pixel detector could not extract visual signals.']};}}
async function loadNews(){try{const d=await fetchJson(`/api/news?asset=${encodeURIComponent($('asset').value)}&fresh=${Date.now()}`);liveNews=d.items||[];renderMacroNews();return liveNews;}catch(e){liveNews=[];renderMacroNews(e.message);return[];}}
async function loadCalendar(){try{const d=await fetchJson(`/api/calendar?fresh=${Date.now()}`);liveCalendar=d.events||[];renderCalendar();return liveCalendar;}catch(e){liveCalendar=[];renderCalendar(e.message);return[];}}
async function refreshResearchContext(){renderTradingView();liveMarket=await buildMarketContext();await Promise.allSettled([loadNews(),loadCalendar()]);return liveMarket;}
function renderMacroNews(errorMessage=''){if(!liveNews.length){$('newsList').innerHTML=`<article class="news-item"><div class="news-top"><span>NEWS</span><b>OPTIONAL</b></div><h3>No current headlines loaded</h3><p>${escapeHtml(errorMessage||'News is unavailable right now.')}</p></article>`;setText('newsStatus','OPTIONAL');return;}setText('newsStatus','LIVE');$('newsList').innerHTML=liveNews.map(i=>`<article class="news-item"><div class="news-top"><span>${escapeHtml(formatDate(i.pubDate))}</span><b>LIVE</b><em>${escapeHtml(i.source||'News')}</em></div><h3>${escapeHtml(i.title)}</h3><p>Current headline related to ${escapeHtml($('asset').value)}.</p><small>${escapeHtml(i.source||'Market news')}</small></article>`).join('');}
function renderCalendar(errorMessage=''){const filter=$('calendarFilter').value,events=filter==='all'?liveCalendar:liveCalendar.filter(e=>e.currency===filter);if(!events.length){$('calendarList').innerHTML=`<article class="calendar-item"><div class="calendar-date"><strong>CALENDAR</strong><span>Optional</span></div><div class="calendar-event"><h3>No current calendar events loaded</h3><p>${escapeHtml(errorMessage||'The calendar is unavailable right now.')}</p></div></article>`;return;}$('calendarList').innerHTML=events.map(e=>`<article class="calendar-item"><div class="calendar-date"><strong>${escapeHtml(formatDate(e.date))}</strong><span>${escapeHtml(e.currency||'')}</span></div><div class="calendar-event"><div><b>${escapeHtml(e.currency||'')}</b><span class="impact-high">${escapeHtml(e.impact||'EVENT')}</span></div><h3>${escapeHtml(e.title)}</h3><p>Actual: ${escapeHtml(e.actual??'—')} · Forecast: ${escapeHtml(e.forecast??'—')} · Previous: ${escapeHtml(e.previous??'—')}</p></div></article>`).join('');}
$('calendarFilter').addEventListener('change',renderCalendar);
$('asset').addEventListener('change',async()=>{setText('analysisMeta',`${$('asset').value} selected · updating market data`);await refreshResearchContext();});
$('timeframe').addEventListener('change',async()=>{setText('analysisMeta',`${$('asset').value} · ${$('timeframe').value} selected`);await refreshResearchContext();});
function localFallbackAnalysis(){const m=liveMarket||{};const i=m.indicators||{};const price=Number(m.price);let bias='WAIT',score=0,signals=[];if(Number.isFinite(price)&&Number.isFinite(i.ema20)&&Number.isFinite(i.ema50)){if(price>i.ema20){score++;signals.push('Price is above EMA 20.');}else{score--;signals.push('Price is below EMA 20.');}if(i.ema20>i.ema50){score+=2;signals.push('EMA 20 is above EMA 50.');}else{score-=2;signals.push('EMA 20 is below EMA 50.');}if(Number.isFinite(i.rsi14)){if(i.rsi14>55&&i.rsi14<70){score++;signals.push(`RSI ${i.rsi14.toFixed(1)} supports bullish momentum.`);}else if(i.rsi14<45&&i.rsi14>30){score--;signals.push(`RSI ${i.rsi14.toFixed(1)} supports bearish momentum.`);}}bias=score>=2?'BUY':score<=-2?'SELL':'WAIT';}else if(localVisual?.visualBias){bias=localVisual.visualBias==='BULLISH'?'BUY':localVisual.visualBias==='BEARISH'?'SELL':'WAIT';signals=[...(localVisual.signals||[])];}const confidence=price&&i.atr14?Math.min(88,50+Math.abs(score)*10):Math.min(65,35+(localVisual?.chartDensity||0));return{bias,confidence,reason:signals.length?signals.join(' '):'Not enough verified data for a directional trade decision. The safe local result is WAIT.',reasoning:[...signals,'Local rule engine only; no paid AI service was used.',imageReady?'Screenshot was analyzed in the browser with a local pixel scan.':'No screenshot was supplied.'],summary:'Local fallback analysis is active. WAIT is used when the available evidence is mixed or incomplete.',warning:'Educational research only. Do not treat this output as a guaranteed trade signal.',entry:null,stopLoss:null,takeProfit1:null,takeProfit2:null,takeProfit3:null,livePriceUsed:Number.isFinite(price)?price:null,machineDataUsed:Boolean(m.dataAvailable)};}
function renderAnalysis(data){const confidence=Math.max(0,Math.min(100,Number(data.confidence)||0));const bias=data.bias||'WAIT';setText('bias',bias);setText('biasReason',data.reason||'Insufficient evidence for a strong directional conclusion.');setText('confidence',confidence);$('confidenceBar').style.width=`${confidence}%`;setText('currentPrice',formatPrice(data.livePriceUsed));setText('currentPriceNote',data.machineDataUsed?'Local engine used machine-readable OHLC data.':'No machine-readable OHLC data was available.');setText('analysisMeta',`${$('asset').value} · ${$('timeframe').value} · LOCAL ENGINE · ${formatDate(data.analyzedAt||new Date().toISOString())}`);setText('researchSummary',data.summary||data.reason||'No summary returned.');setText('entryLevel',formatPrice(data.entry));setText('stopLossLevel',formatPrice(data.stopLoss));setText('tp1Level',formatPrice(data.takeProfit1));setText('tp2Level',formatPrice(data.takeProfit2));setText('tp3Level',formatPrice(data.takeProfit3));$('reasoning').innerHTML=[...(Array.isArray(data.reasoning)?data.reasoning:[]),`Price context: ${data.priceContext||'No numeric price was available.'}`,`Macro risk: ${data.newsRisk||'UNKNOWN'}.`].map(x=>`<li>${escapeHtml(x)}</li>`).join('');const warning=data.warning||'';$('warningBox').hidden=!warning;$('warningBox').textContent=warning;$('results').scrollIntoView({behavior:'smooth',block:'start'});}
analyzeBtn.addEventListener('click',async()=>{analyzeBtn.classList.add('loading');analyzeBtn.disabled=true;analyzeBtn.querySelector('span').textContent=imageReady?'Analyzing locally + market…':'Analyzing locally…';setText('analysisMeta','Detecting chart information locally…');try{if(imageReady&&!localVisual)localVisual=analyzeChartImage(preview);liveMarket=await refreshResearchContext();const payload={image:imageReady?imageDataUrl:null,visualAnalysis:localVisual,asset:$('asset').value,timeframe:$('timeframe').value,style:$('style').value,risk:$('risk').value,market:liveMarket,news:$('includeNews').checked?liveNews:[],calendar:$('includeNews').checked?liveCalendar:[]};let data;try{data=await fetchJson('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});}catch(e){data=localFallbackAnalysis();data.analyzedAt=new Date().toISOString();data.reasoning=[...(data.reasoning||[]),`Backend unavailable: ${e.message}. Browser-local analysis continued instead.`];}renderAnalysis(data);}catch(error){renderAnalysis({...localFallbackAnalysis(),reason:`Local analysis completed with limited data. ${error.message}`,analyzedAt:new Date().toISOString(),warning:'Limited-data mode: the application could not obtain a verified numeric market feed, so no entry, stop-loss or take-profit levels were invented.'});}finally{analyzeBtn.querySelector('span').textContent='Analyze selected market';analyzeBtn.disabled=false;analyzeBtn.classList.remove('loading');}});
renderMacroNews();renderCalendar();renderTradingView();refreshResearchContext().catch(()=>{});