"use client";
import {useEffect,useState} from "react";
import {Activity,RefreshCw,Search,ShieldCheck,BrainCircuit,BarChart3} from "lucide-react";
import MarketChart from "@/components/MarketChart";
import {analyzeMarket,backtestMarket,marketHistory,Analysis,MarketHistory} from "@/lib/api";

const fmt=(n:number|null|undefined)=>n==null?"—":n>=100?n.toLocaleString(undefined,{maximumFractionDigits:2}):n.toFixed(5);

export default function Home(){
 const [symbol,setSymbol]=useState("XAUUSD"),[query,setQuery]=useState(""),[tf,setTf]=useState("1d"),[analysis,setAnalysis]=useState<Analysis|null>(null),[history,setHistory]=useState<MarketHistory|null>(null),[bt,setBt]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const [h,a]=await Promise.all([marketHistory(symbol,"6mo",tf),analyzeMarket(symbol,"6mo",tf)]);setHistory(h);setAnalysis(a)}catch(e){setError(e instanceof Error?e.message:"API request failed")}finally{setLoading(false)}};
 useEffect(()=>{load()},[symbol,tf]);
 const runBT=async()=>{try{setBt(await backtestMarket(symbol))}catch(e){setError(e instanceof Error?e.message:"Backtest failed")}};
 const tone=analysis?.direction==="BULLISH"?"positive":analysis?.direction==="BEARISH"?"negative":"neutral";
 const rr=analysis?.entry&&analysis?.stop_loss&&analysis?.take_profit?Math.abs(analysis.take_profit-analysis.entry)/Math.max(1e-9,Math.abs(analysis.entry-analysis.stop_loss)):null;
 return <div><header className="topbar"><div className="brand"><span className="brandmark"><Activity size={20}/></span>AI Market Analyzer <span className="mono text-[9px] text-[var(--green)]">PRO</span></div><div className="status"><i className="dot"/>REAL DATA ENGINE</div></header>
 <main className="wrap"><section className="hero"><div><div className="eyebrow">QUANTITATIVE MARKET INTELLIGENCE</div><h1>Analyze markets.<br/><span>Test the thesis.</span></h1><p className="sub">Real market-data pipeline with technical analysis, statistical forecasting, signal levels and historical strategy testing. No synthetic prices are presented as live data.</p></div></section>
 <div className="toolbar"><div className="field"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ticker e.g. XAUUSD"/><button onClick={()=>{if(query.trim())setSymbol(query.trim().toUpperCase());setQuery("")}}>ANALYZE</button></div><select className="select" value={tf} onChange={e=>setTf(e.target.value)}><option value="1d">1D</option><option value="1h">1H</option><option value="15m">15M</option><option value="5m">5M</option></select><button className="button" onClick={load}><RefreshCw size={14}/>REFRESH</button><button className="button" onClick={runBT}>BACKTEST</button></div>
 {error&&<div className="card mt-4 p-4 text-[var(--negative)]">{error}</div>}
 {loading&&!analysis?<div className="card mt-4 p-8">Loading real market data…</div>:analysis&&history?<><section className="grid kpis mt-4"><div className="card kpi"><div className="eyebrow">MARKET STATE</div><strong className={tone}>{analysis.direction}</strong><p>{analysis.setup}</p></div><div className="card kpi"><div className="eyebrow">CURRENT PRICE</div><strong>{fmt(analysis.current_price)}</strong><p>{history.source}</p></div><div className="card kpi"><div className="eyebrow">ANALYTICAL CONFIDENCE</div><strong>{(analysis.confidence*100).toFixed(0)}%</strong><p>Not a probability of profit</p></div><div className="card kpi"><div className="eyebrow">RSI 14</div><strong>{fmt(analysis.indicators.rsi)}</strong><p>Momentum context</p></div></section>
 <section className="grid main-grid mt-4"><article className="card chart-card"><div className="head"><div><div className="eyebrow">{symbol} · {tf}</div><h2>Live market history</h2></div><span className="badge">REAL DATA</span></div><div className="chart"><MarketChart candles={history.candles.map(c=>({...c,time:Math.floor(new Date(c.time).getTime()/1000) as any}))}/></div></article>
 <aside className="side-stack"><article className="card signal"><div className="head"><div><div className="eyebrow">SIGNAL ENGINE</div><h3>Read-only direction</h3></div><span className="badge">NO EXECUTION</span></div><div className={"signal-action "+tone}>{analysis.action}</div><div className="grid level-grid"><div className="level"><span>ENTRY</span><b>{fmt(analysis.entry)}</b></div><div className="level"><span>STOP / INVALIDATION</span><b>{fmt(analysis.stop_loss)}</b></div><div className="level"><span>TAKE PROFIT</span><b>{fmt(analysis.take_profit)}</b></div><div className="level"><span>R:R</span><b>{rr?rr.toFixed(2):"—"}</b></div></div><div className="eyebrow">REASONS</div><ul className="reason mt-2">{analysis.reasons.map((x,i)=><li key={i}>{x}</li>)}</ul></article></aside></section>
 <section className="grid two section"><article className="card"><div className="head"><div><div className="eyebrow">TECHNICAL CORE</div><h3>Indicators</h3></div><BarChart3 size={18}/></div><div className="grid three">{Object.entries(analysis.indicators).map(([k,v])=><div className="indicator" key={k}><span>{k.toUpperCase()}</span><b>{fmt(v as number|null)}</b></div>)}</div></article><article className="card"><div className="head"><div><div className="eyebrow">FORECAST</div><h3>Statistical scenario path</h3></div><BrainCircuit size={18}/></div><p className="sub">The current forecast is a baseline statistical model. It is not represented as a trained neural-network prediction.</p>{analysis.prediction.slice(0,5).map((p,i)=><div className="indicator" key={i}><span>{new Date(p.time).toLocaleDateString()}</span><b>{fmt(p.value)}</b></div>)}</article></section>
 <section className="grid two section"><article className="card"><div className="head"><div><div className="eyebrow">SENTIMENT</div><h3>Fundamental interface</h3></div><BrainCircuit size={18}/></div><p className="sub">{String(analysis.sentiment.status||"Not configured")}. News providers and FinBERT can be connected through the backend without changing the dashboard contract.</p></article><article className="card"><div className="head"><div><div className="eyebrow">RISK NOTES</div><h3>Validation</h3></div><ShieldCheck size={18}/></div><ul className="reason">{analysis.risk_notes.map((x,i)=><li key={i}>{x}</li>)}</ul></article></section>
 {bt&&<section className="card section"><div className="head"><div><div className="eyebrow">BACKTEST</div><h3>{bt.symbol} · {bt.period}</h3></div></div><div className="grid four"><div className="kpi"><span>TOTAL RETURN</span><strong>{(bt.metrics.total_return*100).toFixed(2)}%</strong></div><div className="kpi"><span>MAX DRAWDOWN</span><strong>{(bt.metrics.max_drawdown*100).toFixed(2)}%</strong></div><div className="kpi"><span>SHARPE</span><strong>{bt.metrics.sharpe.toFixed(2)}</strong></div><div className="kpi"><span>OBSERVATIONS</span><strong>{bt.metrics.observations}</strong></div></div></section>}
 </>:null}
 <footer className="footer"><span>AI Market Analyzer PRO</span><span>Analysis only. The system does not place orders.</span></footer></main></div>
}